export const site = { name: 'PREMIUM LUMBER GEORGIA', email: 'giorgiaslamazashvili94@gmail.com', phone: '+380 95 777 1010', location: 'თბილისი, სამგორი, ქინძმარაულის 17', whatsapp: 'https://wa.me/380957771010', socials: { facebook: 'https://www.facebook.com/p/PremiumLumber-Georgia-61592661347496/', instagram: 'https://www.instagram.com/premiumlumbergeorgia/', tiktok: 'https://www.tiktok.com/@premiumlumbergeorgia' } };
export { locales, type Locale } from './locales';
import { newSiteText } from './translations/site';
export const photos = {
 forest: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=2400&q=85',
 wood: 'https://images.unsplash.com/photo-1518730518541-d0843268c287?auto=format&fit=crop&w=1000&q=85',
 logs: 'https://images.unsplash.com/photo-1458966480358-a0ac42de0a7a?auto=format&fit=crop&w=1000&q=85',
};
const baseDictionaries = {
 ka: {
 nav: ['ჩვენ შესახებ', 'პროდუქცია', 'პარტნიორობა', 'წარმოება', 'სიახლეები', 'კონტაქტი'],
 eyebrow: 'ბუნებით შთაგონებული. ხარისხით გამორჩეული.', subtitle: 'ხის მასალა — ტყიდან სახლამდე', down: 'აღმოაჩინე მეტი', label: '01 / ჩვენ შესახებ', title: 'ბუნებრივი მასალა.\nუსაზღვრო შესაძლებლობები.', intro: 'ხე ნებისმიერი დიდი იდეის დასაწყისია. ჩვენ ვაერთიანებთ ბუნების სიძლიერესა და საქმის სიყვარულს, რათა თქვენს პროექტს მყარი საფუძველი შევუქმნათ.',
 features: [['ახალგაზრდა გუნდი', 'ახალი ხედვა, ენერგია და საქმისადმი განსაკუთრებული ყურადღება.'], ['სამი საწარმო', 'წარმოების სამი მიმართულება — ერთიანი ხარისხის სტანდარტით.'], ['მსოფლიო ექსპორტი', 'ღია ვართ საერთაშორისო პარტნიორობისა და ახალი ბაზრებისთვის.'], ['ფიჭვის ხის მასალა', 'ბუნებრივი ტექსტურა, სიმტკიცე და მასალის მრავალფეროვნება.'], ['სწრაფი განვითარება', 'უწყვეტი წინსვლა და თანამედროვე მიდგომები წარმოებაში.'], ['მოქნილი მიდგომა', 'თქვენს პროექტზე მორგებული ზომები და თანამშრომლობის პირობები.']],
 production: '02 / ჩვენი პროდუქცია', productTitle: 'ხარისხი, რომელსაც გრძნობ.', productIntro: 'შეარჩიეთ ბუნებრივი ხის მასალა თქვენი შემდეგი პროექტისთვის.', all: 'პროდუქციის ნახვა', more: 'ვრცლად', products: ['დახერხილი ფიცარი', 'ხის ძელი', 'შალაშინით დამუშავებული ხე', 'ხის მოპირკეთება', 'ტერასის ფიცარი', 'ხის პანელები'], categories: ['მშენებლობისთვის', 'მყარი კონსტრუქციებისთვის', 'ზუსტი დეტალებისთვის', 'ინტერიერისა და ფასადისთვის', 'გარე სივრცეებისთვის', 'ავეჯისა და ინტერიერისთვის'],
 details: 'ზომები, ხის სახეობა და დამუშავების პირობები შეთანხმდება თქვენი პროექტის მოთხოვნების მიხედვით. დეტალებისა და შეთავაზებისთვის დაგვიკავშირდით.', inquiry: 'შეთავაზების მოთხოვნა', close: 'დახურვა', partnership: 'ერთად შევქმნათ მეტი.', partnershipText: 'არქიტექტორებს, მშენებლებსა და დისტრიბუტორებს ვთავაზობთ პროექტზე მორგებულ თანამშრომლობას.', manufacturing: 'ხის ბუნებიდან — თქვენს პროექტამდე.', manufacturingText: 'შერჩევა, დამუშავება და მომზადება. ყველა ეტაპზე ყურადღება მასალასა და დეტალებს ეთმობა.', news: 'სიახლეები ტყიდან და საწარმოდან', newsText: 'კომპანიის სიახლეები და ახალი პროდუქტები მალე გამოჩნდება აქ.', contact: 'თქვენი იდეა იწყება აქ.', contactText: 'მოგვიყევით თქვენი პროექტის შესახებ.', links: 'სწრაფი ბმულები', find: 'დაგვიკავშირდით', rights: 'ყველა უფლება დაცულია.', note: 'სადემონსტრაციო კონტაქტები', menu: 'მენიუ', skip: 'მთავარ შინაარსზე გადასვლა', footer: 'ბუნების ძალა. თქვენი სივრცისთვის.',
 },
 en: {
 nav: ['About us', 'Production', 'Partnership', 'Manufacturing', 'News', 'Contacts'], eyebrow: 'ROOTED IN NATURE. CRAFTED FOR YOU.', subtitle: 'Timber — from forest to home', down: 'SCROLL TO EXPLORE', label: '01 / WHO WE ARE', title: 'Natural material.\nEndless possibilities.', intro: 'Every great idea starts with something real. We bring together the strength of nature and a passion for our craft to give your project a solid foundation.',
 features: [['Young team', 'Fresh perspectives, new energy, and a personal commitment to every project.'], ['Three factories', 'Three production directions, brought together by one quality standard.'], ['World export', 'Open to international partnerships and new markets around the world.'], ['Timber from pine', 'Natural character, dependable strength, and remarkable versatility.'], ['Rapid growth', 'Always moving forward with modern approaches to timber production.'], ['Flexible approach', 'Dimensions and partnership terms tailored to the needs of your project.']],
 production: '02 / OUR PRODUCTION', productTitle: 'Quality you can feel.', productIntro: 'Discover the right natural timber for your next project.', all: 'Explore products', more: 'MORE', products: ['Sawn timber', 'Wooden beams', 'Planed timber', 'Wood cladding', 'Decking boards', 'Wood panels'], categories: ['FOR EVERY BUILD', 'A STRONG FOUNDATION', 'PRECISION IN EVERY DETAIL', 'INTERIORS & FACADES', 'MADE FOR THE OUTDOORS', 'FURNITURE & INTERIORS'], details: 'Dimensions, wood species, and finish are agreed according to your project requirements. Contact us for product availability and a tailored quotation.', inquiry: 'Request a quote', close: 'Close', partnership: 'Good things grow together.', partnershipText: 'Project-focused partnerships for architects, builders, and distributors.', manufacturing: 'From its natural roots to your project.', manufacturingText: 'Selection, processing, and preparation. Care for the material and attention to detail at every stage.', news: 'From the forest & the workshop', newsText: 'Company updates and new product announcements are coming soon.', contact: 'Your next idea starts here.', contactText: 'Tell us what you are planning to build.', links: 'Explore', find: 'Get in touch', rights: 'All rights reserved.', note: 'Demo contact information', menu: 'Menu', skip: 'Skip to content', footer: 'The strength of nature. For your space.',
 },
 ru: {
 nav: ['О компании', 'Продукция', 'Партнёрство', 'Производство', 'Новости', 'Контакты'], eyebrow: 'ВДОХНОВЛЕНО ПРИРОДОЙ. СОЗДАНО ДЛЯ ВАС.', subtitle: 'Древесина — от леса до дома', down: 'УЗНАТЬ БОЛЬШЕ', label: '01 / О НАС', title: 'Природный материал.\nБезграничные возможности.', intro: 'Каждая большая идея начинается с настоящего. Мы объединяем силу природы и любовь к своему делу, чтобы создать прочную основу для вашего проекта.',
 features: [['Молодая команда', 'Свежий взгляд, энергия и внимание к каждому проекту.'], ['Три завода', 'Три направления производства с единым стандартом качества.'], ['Мировой экспорт', 'Открыты для международного партнёрства и новых рынков.'], ['Древесина сосны', 'Естественная текстура, прочность и универсальность материала.'], ['Быстрое развитие', 'Постоянное движение вперёд и современные методы производства.'], ['Гибкий подход', 'Размеры и условия сотрудничества под задачи вашего проекта.']], production: '02 / НАША ПРОДУКЦИЯ', productTitle: 'Качество, которое ощущаешь.', productIntro: 'Выберите натуральную древесину для вашего следующего проекта.', all: 'Смотреть продукцию', more: 'ПОДРОБНЕЕ', products: ['Обрезная доска', 'Деревянный брус', 'Строганая древесина', 'Облицовка из дерева', 'Террасная доска', 'Деревянные панели'], categories: ['ДЛЯ СТРОИТЕЛЬСТВА', 'ПРОЧНАЯ ОСНОВА', 'ТОЧНОСТЬ В ДЕТАЛЯХ', 'ИНТЕРЬЕРЫ И ФАСАДЫ', 'ДЛЯ ОТКРЫТЫХ ПРОСТРАНСТВ', 'МЕБЕЛЬ И ИНТЕРЬЕРЫ'], details: 'Размеры, порода дерева и обработка согласовываются под требования вашего проекта. Свяжитесь с нами для уточнения наличия и получения предложения.', inquiry: 'Запросить предложение', close: 'Закрыть', partnership: 'Вместе создадим больше.', partnershipText: 'Сотрудничество для архитекторов, строителей и дистрибьюторов с учётом задач проекта.', manufacturing: 'От природы — к вашему проекту.', manufacturingText: 'Отбор, обработка и подготовка. Внимание к материалу и деталям на каждом этапе.', news: 'Новости леса и мастерской', newsText: 'Новости компании и новые продукты скоро появятся здесь.', contact: 'Ваша идея начинается здесь.', contactText: 'Расскажите нам о вашем проекте.', links: 'Навигация', find: 'Связаться с нами', rights: 'Все права защищены.', note: 'Демонстрационные контакты', menu: 'Меню', skip: 'Перейти к содержимому', footer: 'Сила природы. Для вашего пространства.',
 }
};
export type Dictionary = typeof baseDictionaries.en;
export const dictionaries = { ...baseDictionaries, ...newSiteText };
