import type { Locale } from '../locales';
type Common = { language: string; nature: string; forestHome: string; rooted: string; location: string; country: string; newsTitle: string; newsEmpty: string; errorTitle: string; errorBody: string; retry: string; notFound: string; notFoundBody: string; home: string };
export const commonText: Record<Locale, Common> = {
 ka: { language: 'ენის არჩევა', nature: 'ბუნება. მასალა. შესაძლებლობა.', forestHome: 'ტყიდან სახლამდე', rooted: 'ბუნებით შთაგონებული.', location: 'თბილისი, საქართველო', country: 'საქართველო', newsTitle: 'ბლოგი და სიახლეები', newsEmpty: 'სიახლეები მალე დაემატება.', errorTitle: 'გვერდი დროებით მიუწვდომელია', errorBody: 'გთხოვთ, სცადოთ ხელახლა ცოტა ხანში.', retry: 'ხელახლა ცდა', notFound: 'გვერდი ვერ მოიძებნა', notFoundBody: 'მოთხოვნილი გვერდი არ არსებობს.', home: 'მთავარ გვერდზე დაბრუნება' },
 en: { language: 'Choose language', nature: 'NATURE. MATERIAL. POSSIBILITY.', forestHome: 'FROM FOREST TO HOME', rooted: 'ROOTED IN NATURE.', location: 'Tbilisi, Georgia', country: 'GEORGIA', newsTitle: 'News & stories', newsEmpty: 'Stories will be published soon.', errorTitle: 'This page is temporarily unavailable', errorBody: 'Please try again in a moment.', retry: 'Try again', notFound: 'Page not found', notFoundBody: 'The requested page does not exist.', home: 'Back to home' },
 ru: { language: 'Выбрать язык', nature: 'ПРИРОДА. МАТЕРИАЛ. ВОЗМОЖНОСТИ.', forestHome: 'ОТ ЛЕСА ДО ДОМА', rooted: 'ВДОХНОВЛЕНО ПРИРОДОЙ.', location: 'Тбилиси, Грузия', country: 'ГРУЗИЯ', newsTitle: 'Новости и статьи', newsEmpty: 'Скоро здесь появятся новости.', errorTitle: 'Страница временно недоступна', errorBody: 'Попробуйте ещё раз чуть позже.', retry: 'Попробовать снова', notFound: 'Страница не найдена', notFoundBody: 'Запрашиваемая страница не существует.', home: 'На главную' },
 uk: { language: 'Обрати мову', nature: 'ПРИРОДА. МАТЕРІАЛ. МОЖЛИВОСТІ.', forestHome: 'ВІД ЛІСУ ДО ОСЕЛІ', rooted: 'НАТХНЕННІ ПРИРОДОЮ.', location: 'Тбілісі, Грузія', country: 'ГРУЗІЯ', newsTitle: 'Новини та історії', newsEmpty: 'Незабаром тут з’являться новини.', errorTitle: 'Сторінка тимчасово недоступна', errorBody: 'Спробуйте ще раз трохи згодом.', retry: 'Спробувати ще раз', notFound: 'Сторінку не знайдено', notFoundBody: 'Запитувана сторінка не існує.', home: 'На головну' },
 he: { language: 'בחירת שפה', nature: 'טבע. חומר. אפשרויות.', forestHome: 'מהיער עד הבית', rooted: 'בהשראת הטבע.', location: 'טביליסי, גאורגיה', country: 'גאורגיה', newsTitle: 'חדשות וסיפורים', newsEmpty: 'חדשות יפורסמו כאן בקרוב.', errorTitle: 'הדף אינו זמין כרגע', errorBody: 'נסו שוב בעוד רגע.', retry: 'ניסיון נוסף', notFound: 'הדף לא נמצא', notFoundBody: 'הדף המבוקש אינו קיים.', home: 'חזרה לדף הבית' },
 ar: { language: 'اختيار اللغة', nature: 'طبيعة. خامة. إمكانات.', forestHome: 'من الغابة إلى المنزل', rooted: 'من وحي الطبيعة.', location: 'تبليسي، جورجيا', country: 'جورجيا', newsTitle: 'أخبار وقصص', newsEmpty: 'ستنشر الأخبار هنا قريبًا.', errorTitle: 'هذه الصفحة غير متاحة مؤقتًا', errorBody: 'يرجى المحاولة مجددًا بعد قليل.', retry: 'حاول مجددًا', notFound: 'الصفحة غير موجودة', notFoundBody: 'الصفحة المطلوبة غير موجودة.', home: 'العودة إلى الرئيسية' },
};
