import { newCheckoutText } from '../translations/checkout';
export const checkoutBase = {
  ka: {
    title: 'შეკვეთის გაფორმება', subtitle: 'დატოვეთ მოთხოვნა — დეტალებს თქვენთან ერთად დავაზუსტებთ.', noPayment: 'ონლაინ გადახდის გარეშე', contact: 'საკონტაქტო ინფორმაცია', delivery: 'მიწოდება', fullName: 'სახელი და გვარი', phone: 'ტელეფონი', email: 'ელფოსტა', city: 'ქალაქი', address: 'მისამართი', deliveryMethod: 'მიწოდების მეთოდი', pickup: 'თვითგატანა', transport: 'ჩვენი ტრანსპორტი', other: 'სხვა', comment: 'კომენტარი', commentHint: 'ზომები, დამატებითი მოთხოვნები ან მიწოდების მითითებები', optional: 'არასავალდებულო', summary: 'თქვენი შეკვეთა', estimate: 'სავარაუდო ჯამი', estimateNote: 'მიწოდების ღირებულება არ შედის. საბოლოო ფასი და ხელმისაწვდომობა დადასტურდება შეკვეთის განხილვისას.', submit: 'შეკვეთის გაგზავნა', submitting: 'იგზავნება…', cartLink: 'შეკვეთის გაფორმება', editCart: 'კალათის შეცვლა', successTitle: 'შეკვეთა მიღებულია', successText: 'თქვენი მოთხოვნა შენახულია. გუნდი მითითებულ ტელეფონზე დაგიკავშირდებათ დეტალების დასაზუსტებლად.', orderNumber: 'შეკვეთის ნომერი', newStatus: 'ახალი', status: 'სტატუსი', noCharge: 'თანხა არ ჩამოჭრილა. ონლაინ გადახდა არ არის საჭირო.', loading: 'კალათა იტვირთება…', empty: 'შეკვეთის გასაფორმებლად დაამატეთ პროდუქტი კალათაში.', back: 'კატალოგში დაბრუნება', saveQuantity: 'რაოდენობის შენახვა', quantitySaved: 'რაოდენობა განახლებულია', unitNote: 'ერთეული არჩეულია პროდუქტის გვერდზე.', errorTitle: 'შეკვეთა ვერ დადასტურდა', retry: 'კალათა შენარჩუნებულია. სცადეთ ხელახლა — იგივე მოთხოვნა არ გაორმაგდება.', invalidCart: 'კალათაში არსებული პროდუქტი ან რაოდენობა არასწორია. გადაამოწმეთ კალათა.', conflict: 'გაგზავნის მონაცემები შეიცვალა. განაახლეთ გვერდი და სცადეთ ხელახლა.', cartNote: 'სავარაუდო ღირებულება. შეკვეთა იგზავნება გაფორმების გვერდიდან.',
    errors: { name: 'მიუთითეთ სახელი და გვარი (2–120 სიმბოლო).', phone: 'მიუთითეთ მოქმედი ტელეფონის ნომერი (7–15 ციფრი).', email: 'მიუთითეთ სწორი ელფოსტის მისამართი.', city: 'ქალაქი სავალდებულოა მიწოდებისას (მაქს. 100 სიმბოლო).', address: 'მისამართი სავალდებულოა მიწოდებისას (მაქს. 300 სიმბოლო).', comment: 'კომენტარი არ უნდა აღემატებოდეს 2000 სიმბოლოს.', delivery: 'აირჩიეთ მიწოდების მეთოდი.' },
  },
  en: {
    title: 'Request your order', subtitle: 'Send your request — we will confirm the details with you.', noPayment: 'No online payment', contact: 'Contact details', delivery: 'Delivery', fullName: 'Full name', phone: 'Phone', email: 'Email', city: 'City', address: 'Address', deliveryMethod: 'Delivery method', pickup: 'Pickup', transport: 'Our transport', other: 'Other', comment: 'Comment', commentHint: 'Dimensions, additional requirements or delivery instructions', optional: 'Optional', summary: 'Your order', estimate: 'Estimated total', estimateNote: 'Delivery is not included. Final pricing and availability will be confirmed when we review your request.', submit: 'Send order request', submitting: 'Sending…', cartLink: 'Proceed to checkout', editCart: 'Edit cart', successTitle: 'Order received', successText: 'Your request has been saved. Our team will call the supplied phone number to confirm the details.', orderNumber: 'Order number', newStatus: 'New', status: 'Status', noCharge: 'You have not been charged. No online payment is required.', loading: 'Loading your cart…', empty: 'Add a product to your cart before checkout.', back: 'Back to catalog', saveQuantity: 'Save quantity', quantitySaved: 'Quantity updated', unitNote: 'The unit is selected on the product page.', errorTitle: 'We could not confirm your order', retry: 'Your cart has been kept. Please retry — the same request will not create a duplicate.', invalidCart: 'A product or quantity in your cart is invalid. Please review your cart.', conflict: 'The submission data changed. Refresh the page and try again.', cartNote: 'Estimated cost. Submit your request from the checkout page.',
    errors: { name: 'Enter your full name (2–120 characters).', phone: 'Enter a valid phone number (7–15 digits).', email: 'Enter a valid email address.', city: 'City is required for delivery (max. 100 characters).', address: 'Address is required for delivery (max. 300 characters).', comment: 'Comment must be 2,000 characters or fewer.', delivery: 'Choose a delivery method.' },
  },
  ru: {
    title: 'Оформление заказа', subtitle: 'Отправьте заявку — мы уточним детали вместе с вами.', noPayment: 'Без онлайн-оплаты', contact: 'Контактные данные', delivery: 'Доставка', fullName: 'Имя и фамилия', phone: 'Телефон', email: 'Электронная почта', city: 'Город', address: 'Адрес', deliveryMethod: 'Способ доставки', pickup: 'Самовывоз', transport: 'Наш транспорт', other: 'Другое', comment: 'Комментарий', commentHint: 'Размеры, дополнительные требования или инструкции по доставке', optional: 'Необязательно', summary: 'Ваш заказ', estimate: 'Предварительная сумма', estimateNote: 'Доставка не включена. Окончательная цена и наличие будут подтверждены при рассмотрении заявки.', submit: 'Отправить заказ', submitting: 'Отправка…', cartLink: 'Оформить заказ', editCart: 'Изменить корзину', successTitle: 'Заказ принят', successText: 'Ваша заявка сохранена. Мы позвоним по указанному номеру, чтобы уточнить детали.', orderNumber: 'Номер заказа', newStatus: 'Новый', status: 'Статус', noCharge: 'Деньги не списаны. Онлайн-оплата не требуется.', loading: 'Загрузка корзины…', empty: 'Добавьте товар в корзину для оформления заказа.', back: 'Вернуться в каталог', saveQuantity: 'Сохранить количество', quantitySaved: 'Количество обновлено', unitNote: 'Единица выбирается на странице товара.', errorTitle: 'Не удалось подтвердить заказ', retry: 'Корзина сохранена. Попробуйте ещё раз — тот же запрос не создаст дубликат.', invalidCart: 'В корзине некорректный товар или количество. Проверьте корзину.', conflict: 'Данные запроса изменились. Обновите страницу и повторите попытку.', cartNote: 'Предварительная стоимость. Отправьте заявку со страницы оформления.',
    errors: { name: 'Введите имя и фамилию (2–120 символов).', phone: 'Введите корректный телефон (7–15 цифр).', email: 'Введите корректный адрес электронной почты.', city: 'Для доставки укажите город (до 100 символов).', address: 'Для доставки укажите адрес (до 300 символов).', comment: 'Комментарий не должен превышать 2000 символов.', delivery: 'Выберите способ доставки.' },
  },
};

export const checkoutText = { ...checkoutBase, ...newCheckoutText };
