'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { Package, ShoppingBag, FolderTree, Newspaper, LogOut, Plus, RefreshCw } from 'lucide-react';
import { CategoryEditor, ProductEditor, PostEditor, emptyPost, emptyProduct, type EditableCategory, type EditableProduct, type EditablePost } from './editors';
import { InventoryPanel, OrderInventoryActions } from './inventory';
import { statusLabels } from '@/lib/admin/validation';
import { BrandLogo } from '@/components/brand-logo';

type Resource = 'inventory' | 'orders' | 'products' | 'categories' | 'posts';
type Order = { inventoryDeductedAt?: string | null; inventoryReturnedAt?: string | null; id: number; status: keyof typeof statusLabels; notes: string; updatedAt: string; createdAt: string; fullName: string; phone: string; email: string | null; city: string | null; address: string | null; deliveryMethod: string; comment: string | null; totalCents: number; items: { id: number; nameKa: string; thickness: number; width: number; length: number; unit: string; quantityMilli: number; totalCents: number }[] };
type Item = EditableProduct | EditableCategory | EditablePost | Order;
const tabs = [{ id: 'inventory' as const, label: 'ნაშთები', icon: Package }, { id: 'orders' as const, label: 'შეკვეთები', icon: ShoppingBag }, { id: 'products' as const, label: 'პროდუქტები', icon: Package }, { id: 'categories' as const, label: 'კატეგორიები', icon: FolderTree }, { id: 'posts' as const, label: 'ბლოგი / სიახლეები', icon: Newspaper }];
const money = (cents: number) => `${(cents / 100).toLocaleString('ka-GE', { minimumFractionDigits: 2 })} ₾`;
async function api(resource: string, method = 'GET', body?: unknown) {
  const response = await fetch(`/api/admin/${resource}`, { method, cache: 'no-store', ...(body ? { headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : {}) });
  const result = await response.json();
  if (response.status === 401) { window.location.assign('/admin/login'); throw new Error('სესია დასრულდა.'); }
  if (!response.ok) throw new Error([result.error, ...(result.fields || [])].join('\n'));
  return result;
}
export function AdminDashboard({ email }: { email: string }) {
  const [tab, setTab] = useState<Resource>('orders'); const [page, setPage] = useState(1); const [status, setStatus] = useState('');
  const [items, setItems] = useState<Item[]>([]); const [categories, setCategories] = useState<EditableCategory[]>([]); const [count, setCount] = useState(0);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [editing, setEditing] = useState<{ value: Item; existing: boolean } | null>(null); const [revision, setRevision] = useState(0);
  const reload = useCallback(() => setRevision(n => n + 1), []);
  useEffect(() => {
    if (tab === 'inventory') return;
    let active = true; setLoading(true); setError(''); setItems([]);
    Promise.all([api(`${tab}?page=${page}&status=${status}`), api('categories')]).then(([data, cats]) => { if (active) { setItems(data.items); setCount(data.count ?? data.items.length); setCategories(cats.items); } }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [tab, page, status, revision]);
  const save = async (value: Item) => { setBusy(true); setError(''); try { await api(tab, editing?.existing ? 'PUT' : 'POST', value); setEditing(null); setNotice('ცვლილებები შენახულია.'); reload(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const remove = async (id: string) => { if (!window.confirm('წაიშალოს ეს ჩანაწერი? აღდგენა შეუძლებელი იქნება.')) return; setBusy(true); setError(''); try { await api(tab, 'DELETE', { id }); setNotice('ჩანაწერი წაიშალა.'); reload(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const title = tabs.find(t => t.id === tab)!.label;
  return <><aside className="admin-sidebar"><BrandLogo href="/ka" inverse className="admin-brand"/><span className="admin-brand-caption">მართვის პანელი</span><nav aria-label="ადმინისტრაციის მენიუ">{tabs.map(t => <button key={t.id} className={tab === t.id ? 'is-active' : ''} onClick={() => { setTab(t.id); setPage(1); setStatus(''); setEditing(null); setNotice(''); }}><t.icon size={19}/>{t.label}</button>)}</nav><div className="admin-account"><small>{email}</small><button onClick={async () => { try { await api('logout', 'POST'); window.location.assign('/admin/login'); } catch (e) { setError((e as Error).message); } }}><LogOut size={16}/>გასვლა</button></div></aside>
    <main className="admin-main"><header className="admin-header"><div><p className="admin-kicker">PREMIUM LUMBER GEORGIA / ადმინისტრაცია</p><h1>{editing ? `${editing.existing ? 'რედაქტირება' : 'დამატება'} — ${title}` : title}</h1></div><Link href="/ka" target="_blank">საიტის ნახვა ↗</Link></header>
      {error && <p className="admin-error" role="alert">{error}</p>}{notice && !editing && <p className="admin-notice" role="status">{notice}</p>}
      {tab === 'inventory' ? <InventoryPanel/> : editing ? <section className="admin-panel"><button className="admin-secondary" disabled={busy} onClick={() => { setEditing(null); setError(''); }}>← სიაში დაბრუნება</button>{tab === 'products' ? <ProductEditor initial={editing.value as EditableProduct} categories={categories} existing={editing.existing} busy={busy} onSave={save}/> : tab === 'categories' ? <CategoryEditor initial={editing.value as EditableCategory} existing={editing.existing} busy={busy} onSave={save}/> : tab === 'posts' ? <PostEditor initial={editing.value as EditablePost} existing={editing.existing} busy={busy} onSave={save}/> : <OrderEditor onInventoryDone={() => { setEditing(null); reload(); }} initial={editing.value as Order} busy={busy} onSave={async value => { setBusy(true); setError(''); try { await api('orders', 'PUT', value); setEditing(null); setNotice('შეკვეთა განახლდა.'); reload(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}/>}</section> : <section className="admin-panel"><div className="admin-toolbar"><div><strong>{loading ? 'იტვირთება…' : `${count} ჩანაწერი`}</strong>{tab === 'orders' && <label>სტატუსი<select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">ყველა სტატუსი</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>}</div><div className="admin-inline"><button className="admin-secondary" onClick={reload} disabled={loading}><RefreshCw size={16}/>განახლება</button>{tab !== 'orders' && <button disabled={loading || busy} onClick={() => { setNotice(''); setEditing({ existing: false, value: tab === 'products' ? emptyProduct(categories[0]?.id || '') : tab === 'posts' ? emptyPost() : { id: '', name: { ka: '', en: '', ru: '', uk: '', he: '', ar: '' } } }); }}><Plus size={16}/>დამატება</button>}</div></div>
        {!loading && !items.length && <div className="admin-empty"><FolderTree size={36}/><h2>ჩანაწერები ჯერ არ არის</h2><p>{tab === 'orders' ? 'მომხმარებლის შეკვეთა აქ გამოჩნდება.' : 'პირველი ჩანაწერის შესაქმნელად დააჭირეთ დამატებას.'}</p></div>}
        {!!items.length && <div className="admin-table-wrap"><table><thead><tr><th>{tab === 'orders' ? 'შეკვეთა / მომხმარებელი' : 'დასახელება'}</th><th>{tab === 'categories' ? 'კოდი' : 'ინფორმაცია'}</th><th>მოქმედება</th></tr></thead><tbody>{items.map((item, index) => {
          const p = item as EditableProduct; const o = item as Order; const post = item as EditablePost; const c = item as EditableCategory;
          return <tr key={String(item.id ?? index)}><td>{tab === 'orders' ? <><strong>ORD-{o.id + 1023}</strong><p>{o.fullName}</p><small>{new Date(o.createdAt).toLocaleString('ka-GE')}</small></> : tab === 'posts' ? <><strong>{post.title.ka}</strong><p>/{post.slug}</p></> : <div className="admin-product-name">{tab === 'products' && <img src={p.images[0]?.src} alt=""/>}<strong>{c.name.ka}</strong></div>}</td><td>{tab === 'orders' ? <><span className={`admin-badge status-${o.status}`}>{statusLabels[o.status]}</span><p>{money(o.totalCents)}</p></> : tab === 'products' ? <><span className="admin-badge">{p.active ? 'გამოქვეყნებული' : 'დამალული'}</span><p>{p.variants.length} ზომა · {categories.find(c => c.id === p.category)?.name.ka}</p></> : tab === 'posts' ? <span className="admin-badge">{post.published ? 'გამოქვეყნებული' : 'დრაფტი'}</span> : c.id}</td><td><div className="admin-inline"><button className="admin-secondary" disabled={busy} onClick={() => { setNotice(''); const value = tab === 'products' ? (({ categoryName, ...rest }) => rest)(p) : tab === 'posts' ? { id: post.id, slug: post.slug, title: post.title, excerpt: post.excerpt, body: post.body, image: post.image || '', published: post.published } : tab === 'categories' ? { id: c.id, name: c.name } : item; setEditing({ value, existing: true }); }}>{tab === 'orders' ? 'დეტალები' : 'რედაქტირება'}</button>{tab !== 'orders' && <button className="admin-danger" disabled={busy} onClick={() => remove(String(item.id))}>წაშლა</button>}</div></td></tr>;
        })}</tbody></table></div>}
        {tab !== 'categories' && count > 25 && <div className="admin-pagination"><button className="admin-secondary" disabled={page === 1 || loading} onClick={() => setPage(p => p - 1)}>← წინა</button><span>{page} / {Math.ceil(count / 25)}</span><button className="admin-secondary" disabled={page * 25 >= count || loading} onClick={() => setPage(p => p + 1)}>შემდეგი →</button></div>}
      </section>}
    </main></>;
}
function OrderEditor({ initial, busy, onSave, onInventoryDone }: { onInventoryDone: () => void; initial: Order; busy: boolean; onSave: (value: { id: number; status: Order['status']; notes: string; updatedAt: string }) => void }) {
  const [status, setStatus] = useState(initial.status); const [notes, setNotes] = useState(initial.notes);
  return <div className="admin-order"><h2>ORD-{initial.id + 1023}</h2><OrderInventoryActions order={initial} onDone={onInventoryDone}/><div className="admin-grid"><section><h3>მომხმარებელი</h3><p>{initial.fullName}</p><p>{initial.phone}</p><p>{initial.email}</p></section><section><h3>მიწოდება</h3><p>{{ pickup: 'ადგილზე გატანა', transport: 'ტრანსპორტირება', other: 'სხვა მეთოდი' }[initial.deliveryMethod] ?? initial.deliveryMethod}</p><p>{initial.city} {initial.address}</p></section><section><h3>მომხმარებლის კომენტარი</h3><p className="admin-preserve">{initial.comment || '—'}</p></section></div><div className="admin-table-wrap"><table><thead><tr><th>პროდუქტი / ზომა</th><th>რაოდენობა</th><th>ჯამი</th></tr></thead><tbody>{initial.items.map(item => <tr key={item.id}><td>{item.nameKa}<p>{item.thickness} × {item.width} × {item.length} მმ</p></td><td>{item.quantityMilli / 1000} {item.unit}</td><td>{money(item.totalCents)}</td></tr>)}</tbody></table></div><h3>სულ: {money(initial.totalCents)}</h3><form onSubmit={e => { e.preventDefault(); onSave({ id: initial.id, status, notes, updatedAt: initial.updatedAt }); }}><fieldset disabled={busy} className="admin-form-body"><label>სტატუსი<select value={status} onChange={e => setStatus(e.target.value as Order['status'])}>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>შიდა შენიშვნები<textarea rows={6} maxLength={10000} value={notes} onChange={e => setNotes(e.target.value)}/></label><button disabled={busy}>{busy ? 'ინახება…' : 'ცვლილებების შენახვა'}</button></fieldset></form></div>;
}
