'use client';
import { locales, localeNames, direction } from '@/lib/locales';
import { useState } from 'react';
import type { Localized, Product, ProductVariant } from '@/lib/catalog/types';
export type EditableProduct = Product & { active: boolean };
export type EditablePost = { id?: string; slug: string; title: Localized; excerpt: Localized; body: Localized; image: string; published: boolean };
export type EditableCategory = { id: string; name: Localized };
const blank = (): Localized => ({ ka: '', en: '', ru: '', uk: '', he: '', ar: '' });
const newVariant = (): ProductVariant => ({ id: `size-${crypto.randomUUID()}`, dimensions: { thickness: 25, width: 100, length: 3000 }, price: { amount: 1, currency: 'GEL', unit: 'm3' }, status: 'available' });
export const emptyProduct = (category: string): EditableProduct => ({ id: '', category, name: blank(), description: blank(), shortDescription: blank(), images: [], species: 'pine', grade: 'AB', moisture: 'air-dried', units: ['piece', 'm3', 'm2', 'lm'], active: false, variants: [newVariant()] });
export const emptyPost = (): EditablePost => ({ slug: '', title: blank(), excerpt: blank(), body: blank(), image: '', published: false });
function Translations({ label, value, onChange, multiline = false }: { label: string; value: Localized; onChange: (v: Localized) => void; multiline?: boolean }) {
  return <fieldset className="admin-translations"><legend>{label}</legend>{locales.map(locale => <label key={locale}>{localeNames[locale]}{multiline ? <textarea required rows={4} lang={locale} dir={direction(locale)} value={value[locale] ?? ''} onChange={e => onChange({ ...value, [locale]: e.target.value })}/> : <input required maxLength={250} lang={locale} dir={direction(locale)} value={value[locale] ?? ''} onChange={e => onChange({ ...value, [locale]: e.target.value })}/>}</label>)}</fieldset>;
}
function PhotoUpload({ onUpload }: { onUpload: (url: string) => void }) {
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  return <div><label className="admin-upload">{busy ? 'იტვირთება…' : 'ფოტოს ატვირთვა (JPG / PNG / WebP, მაქს. 5 MB)'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async event => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; if (file.size > 5 * 1024 * 1024) { setError('ფაილი აღემატება 5 MB-ს.'); return; } setBusy(true); setError(''); try { const response = await fetch('/api/admin/upload', { method: 'POST', headers: { 'Content-Type': file.type }, body: file }); const data = await response.json(); if (!response.ok) throw new Error(data.error); onUpload(data.url); } catch (e) { setError(e instanceof Error ? e.message : 'ატვირთვა ვერ შესრულდა.'); } finally { setBusy(false); } }}/></label>{error && <p role="alert" className="admin-error">{error}</p>}</div>;
}
type SaveProps<T> = { initial: T; existing: boolean; busy: boolean; onSave: (value: T) => void };
export function ProductEditor({ initial, existing, busy, onSave, categories }: SaveProps<EditableProduct> & { categories: EditableCategory[] }) {
  const [p, set] = useState(initial); const [image, setImage] = useState('');
  const patch = (change: Partial<EditableProduct>) => set(previous => ({ ...previous, ...change }));
  const variant = (index: number, value: ProductVariant) => patch({ variants: p.variants.map((v, i) => i === index ? value : v) });
  const addPhoto = (src: string) => set(previous => ({ ...previous, images: [...previous.images, { src, alt: previous.name }] }));
  return <form onSubmit={e => { e.preventDefault(); onSave({ ...p, variants: p.variants.map(({ id, dimensions, coverageWidth, price, status }) => ({ id, dimensions, coverageWidth, price, status })), images: p.images.map(photo => ({ ...photo, alt: Object.fromEntries(locales.map(locale => [locale, photo.alt[locale] || p.name[locale]])) as Localized })) }); }}><fieldset disabled={busy} className="admin-form-body"><div className="admin-grid"><label>პროდუქტის კოდი<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={100} disabled={existing} value={p.id} onChange={e => patch({ id: e.target.value })}/><small>ლათინური ასოები, ციფრები, დეფისი</small></label><label>კატეგორია<select required value={p.category} onChange={e => patch({ category: e.target.value })}><option value="">აირჩიეთ</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name.ka}</option>)}</select></label></div>
    <Translations label="დასახელება" value={p.name} onChange={name => patch({ name })}/><Translations label="მოკლე აღწერა" value={p.shortDescription} onChange={shortDescription => patch({ shortDescription })} multiline/><Translations label="სრული აღწერა" value={p.description} onChange={description => patch({ description })} multiline/>
    <div className="admin-grid"><label>ხის ჯიში<select value={p.species} onChange={e => patch({ species: e.target.value as Product['species'] })}><option value="pine">ფიჭვი</option><option value="spruce">ნაძვი</option><option value="larch">ლარიქსი</option></select></label><label>ხარისხი<select value={p.grade} onChange={e => patch({ grade: e.target.value as Product['grade'] })}>{['A', 'B', 'AB', 'Extra'].map(v => <option key={v}>{v}</option>)}</select></label><label>ტენიანობა<select value={p.moisture} onChange={e => patch({ moisture: e.target.value as Product['moisture'] })}><option value="green">სველი</option><option value="air-dried">გამომშრალი</option><option value="kiln-dried">კამერული</option></select></label></div>
    <fieldset><legend>გასაყიდი ერთეულები</legend><div className="admin-inline">{(['piece','m3','m2','lm'] as const).map(unit => <label className="admin-check" key={unit}><input type="checkbox" checked={p.units.includes(unit)} disabled={unit === 'piece'} onChange={e => patch({ units: e.target.checked ? [...p.units, unit] : p.units.filter(u => u !== unit) })}/>{unit}</label>)}</div></fieldset>
    <fieldset><legend>ფოტოები</legend><div className="admin-photos">{p.images.map((photo, i) => <div key={`${photo.src}-${i}`}><img src={photo.src} alt={photo.alt.ka}/><Translations label={`ფოტოს აღწერა ${i + 1}`} value={photo.alt} onChange={alt => patch({ images: p.images.map((item, index) => index === i ? { ...item, alt } : item) })}/><button className="admin-danger" type="button" onClick={() => patch({ images: p.images.filter((_, index) => index !== i) })}>ამოღება</button></div>)}</div><PhotoUpload onUpload={addPhoto}/><label>ან ფოტოს HTTPS მისამართი<input type="url" value={image} onChange={e => setImage(e.target.value)}/></label><button type="button" className="admin-secondary" disabled={!image || p.images.length >= 12} onClick={() => { addPhoto(image); setImage(''); }}>ფოტოს დამატება</button></fieldset>
    <fieldset><legend>ზომები და ფასები</legend><p>ზომები — მილიმეტრებში; ფასი — ლარში არჩეულ ერთეულზე.</p>{p.variants.map((v, i) => <div className="admin-variant" key={v.id}><div className="admin-inline"><strong>ვარიანტი {i + 1}</strong><button type="button" className="admin-danger" disabled={p.variants.length === 1} onClick={() => patch({ variants: p.variants.filter((_, index) => index !== i) })}>ამოღება</button></div><small>{v.id}</small><div className="admin-grid">{(['thickness','width','length'] as const).map(key => <label key={key}>{{ thickness: 'სისქე', width: 'სიგანე', length: 'სიგრძე' }[key]}<input required type="number" min="0.01" step="0.01" value={v.dimensions[key]} onChange={e => variant(i, { ...v, dimensions: { ...v.dimensions, [key]: Number(e.target.value) } })}/></label>)}<label>დაფარვის სიგანე<input type="number" min="0.01" max={v.dimensions.width} step="0.01" value={v.coverageWidth ?? ''} onChange={e => variant(i, { ...v, coverageWidth: e.target.value ? Number(e.target.value) : undefined })}/></label><label>ფასი (₾)<input required type="number" min="0.01" max="10000000" step="0.01" value={v.price.amount} onChange={e => variant(i, { ...v, price: { ...v.price, amount: Number(e.target.value) } })}/></label><label>ფასის ერთეული<select value={v.price.unit} onChange={e => variant(i, { ...v, price: { ...v.price, unit: e.target.value as ProductVariant['price']['unit'] } })}>{['m3','m2','lm','piece'].map(u => <option key={u}>{u}</option>)}</select></label><label>ხელმისაწვდომობა<select value={v.status} onChange={e => variant(i, { ...v, status: e.target.value as ProductVariant['status'] })}><option value="available">მარაგშია</option><option value="on-order">შეკვეთით</option></select></label></div></div>)}<button type="button" className="admin-secondary" disabled={p.variants.length >= 50} onClick={() => patch({ variants: [...p.variants, newVariant()] })}>+ ზომის დამატება</button></fieldset>
    <label className="admin-check"><input type="checkbox" checked={p.active} onChange={e => patch({ active: e.target.checked })}/>გამოჩნდეს საიტზე</label><button disabled={busy || !p.images.length} type="submit">{busy ? 'ინახება…' : 'პროდუქტის შენახვა'}</button></fieldset></form>;
}
export function CategoryEditor({ initial, existing, busy, onSave }: SaveProps<EditableCategory>) {
  const [p, set] = useState(initial);
  return <form onSubmit={e => { e.preventDefault(); onSave(p); }}><fieldset disabled={busy} className="admin-form-body"><label>კოდი<input required disabled={existing} pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={100} value={p.id} onChange={e => set({ ...p, id: e.target.value })}/></label><Translations label="დასახელება" value={p.name} onChange={name => set({ ...p, name })}/><button disabled={busy}>შენახვა</button></fieldset></form>;
}
export function PostEditor({ initial, busy, onSave }: SaveProps<EditablePost>) {
  const [p, set] = useState(initial);
  return <form onSubmit={e => { e.preventDefault(); onSave(p); }}><fieldset disabled={busy} className="admin-form-body"><label>მისამართის კოდი<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={100} value={p.slug} onChange={e => set({ ...p, slug: e.target.value })}/></label><Translations label="სათაური" value={p.title} onChange={title => set({ ...p, title })}/><Translations label="მოკლე აღწერა" value={p.excerpt} onChange={excerpt => set({ ...p, excerpt })} multiline/><Translations label="სტატიის ტექსტი" value={p.body} onChange={body => set({ ...p, body })} multiline/><label>ფოტოს HTTPS მისამართი<input type="url" value={p.image} onChange={e => set({ ...p, image: e.target.value })}/></label>{p.image && <img className="admin-cover" src={p.image} alt="სტატიის ფოტო"/>}<PhotoUpload onUpload={image => set(previous => ({ ...previous, image }))}/><label className="admin-check"><input type="checkbox" checked={p.published} onChange={e => set({ ...p, published: e.target.checked })}/>გამოქვეყნებული</label><button disabled={busy}>სტატიის შენახვა</button></fieldset></form>;
}
