'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { Locale } from '@/lib/site';
import { locales, localeNames, direction } from '@/lib/locales';
import type { Localized, ProductVariant } from '@/lib/catalog/types';
import { dimensionText } from '@/lib/catalog/logic';
import { unitLabels } from '@/lib/catalog/i18n';
import { inventoryText, issueLabel, stockLabel } from '@/lib/inventory/i18n';
import { changedQuantity, stockStatus, type StockIssue } from '@/lib/inventory/quantity';
type Row = ProductVariant & { productId: string; productName: Localized; categoryId: string };
type Movement = { id: string; type: string; quantity: string; beforeQuantity: string; afterQuantity: string; stockUnit: keyof typeof unitLabels; reason: string; note: string; admin: { email: string } | null; createdAt: string };
const types = { SALE: 'sale', RECEIPT: 'receipt', RETURN: 'return', ADJUSTMENT: 'adjustment', DAMAGE: 'damage', INITIAL: 'initial' } as const;
export async function inventoryApi(query: string, locale: Locale, body?: unknown) {
  const response = await fetch(`/api/admin/inventory${query}`, { cache: 'no-store', ...(body ? { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : {}) });
  const result = await response.json(); const t = inventoryText[locale];
  if (!response.ok) throw new Error(result.code === 'INSUFFICIENT_STOCK' ? result.issues.map((issue: StockIssue) => issueLabel(issue, locale)).join('\n') : result.code === 'CONFLICT' ? t.conflict : response.status === 422 ? t.invalid : result.error || t.unavailable);
  return result;
}
export function OrderInventoryActions({ order, onDone }: { order: { id: number; status: string; inventoryDeductedAt?: string | null; inventoryReturnedAt?: string | null }; onDone: () => void }) {
  const [locale, setLocale] = useState<Locale>('ka'); const [busy, setBusy] = useState(false), [error, setError] = useState(''); const t = inventoryText[locale];
  async function act(action: 'sell' | 'return') { setBusy(true); setError(''); try { await inventoryApi('', locale, { orderId: order.id, action }); onDone(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <section dir={direction(locale)} className="admin-variant"><Language value={locale} onChange={setLocale}/><div className="admin-inline"><button type="button" disabled={busy || !!order.inventoryDeductedAt || order.status === 'CANCELLED'} onClick={() => act('sell')}>{t.sold}</button><button type="button" disabled={busy || !order.inventoryDeductedAt || !!order.inventoryReturnedAt || order.status !== 'CANCELLED'} onClick={() => act('return')}>{t.restore}</button></div>{order.inventoryDeductedAt && <p>{t.sale}: {new Date(order.inventoryDeductedAt).toLocaleString(locale)}</p>}{order.inventoryReturnedAt && <p>{t.return}: {new Date(order.inventoryReturnedAt).toLocaleString(locale)}</p>}{error && <p role="alert" className="admin-error">{error}</p>}</section>;
}
function Language({ value, onChange }: { value: Locale; onChange: (v: Locale) => void }) { return <select aria-label="Language" value={value} onChange={e => onChange(e.target.value as Locale)}>{locales.map(l => <option key={l} value={l}>{localeNames[l]}</option>)}</select>; }
export function InventoryPanel() {
  const [locale, setLocale] = useState<Locale>('ka'); const t = inventoryText[locale];
  const [rows, setRows] = useState<Row[]>([]), [categories, setCategories] = useState<{ id: string; name: Localized }[]>([]);
  const [query, setQuery] = useState(''), [category, setCategory] = useState(''), [status, setStatus] = useState(''), [page, setPage] = useState(1), [count, setCount] = useState(0), [revision, setRevision] = useState(0);
  const [error, setError] = useState(''), [loading, setLoading] = useState(false), [selected, setSelected] = useState<Row | null>(null);
  const [history, setHistory] = useState<Row | null>(null);
  const reload = useCallback(() => setRevision(v => v + 1), []);
  useEffect(() => { let active = true; fetch('/api/admin/categories').then(r => r.json()).then(v => { if (active && v.items) setCategories(v.items); }); return () => { active = false; }; }, []);
  useEffect(() => {
    let active = true; setLoading(true); const timer = setTimeout(() => {
      inventoryApi(`?${new URLSearchParams({ q: query, category, status, page: String(page) })}`, locale).then(v => { if (active) { setRows(v.items); setCount(v.count); setError(''); } }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); });
    }, 200); return () => { active = false; clearTimeout(timer); };
  }, [query, category, status, page, revision, locale]);
  return <section className="admin-panel inventory-panel" dir={direction(locale)} lang={locale} aria-busy={loading}>
    <div className="admin-toolbar"><h2>{t.inventory}</h2><Language value={locale} onChange={setLocale}/><button onClick={reload} disabled={loading}>{t.refresh}</button></div>
    <div className="admin-grid"><label>{t.search}<input value={query} maxLength={200} onChange={e => { setQuery(e.target.value); setPage(1); }}/></label><label>{t.category}<select value={category} onChange={e => { setCategory(e.target.value); setPage(1); }}><option value="">{t.all}</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name[locale]}</option>)}</select></label><label>{t.current}<select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">{t.all}</option><option value="low">{t.low}</option><option value="out">{t.out}</option></select></label></div>
    {error && <p role="alert" className="admin-error">{error}</p>}
    <div className="admin-table-wrap"><table><caption>{t.inventory} ({count})</caption><thead><tr><th>{t.search}</th><th>{t.current}</th><th>{t.threshold}</th><th>{t.edit}</th></tr></thead><tbody>{rows.map(v => <tr key={v.id}><td><strong>{v.productName[locale]}</strong><p><bdi>{v.productId} / {v.id}</bdi></p><p><bdi>{dimensionText(v)} mm</bdi></p></td><td><span className={`inventory-status inventory-${stockStatus(v)}`}>{stockLabel(v, locale)}</span><p>{v.stockQuantity} {unitLabels[v.stockUnit ?? 'piece'][locale]}</p></td><td>{v.lowStockThreshold}<p>{v.updatedAt && new Date(v.updatedAt).toLocaleString(locale)}</p></td><td><div className="admin-inline"><button onClick={() => setSelected(v)}>{t.edit}</button><button className="admin-secondary" onClick={() => setHistory(v)}>{t.history}</button></div></td></tr>)}</tbody></table></div>
    <div className="admin-pagination"><button disabled={page === 1 || loading} onClick={() => setPage(p => p - 1)}>{t.previous}</button><span>{page} / {Math.max(1, Math.ceil(count / 25))}</span><button disabled={page * 25 >= count || loading} onClick={() => setPage(p => p + 1)}>{t.next}</button></div>
    {selected && <StockForm row={selected} locale={locale} onClose={() => setSelected(null)} onSaved={() => { setSelected(null); reload(); }}/>} {history && <History row={history} locale={locale} onClose={() => setHistory(null)}/>}
  </section>;
}
function StockForm({ row, locale, onClose, onSaved }: { row: Row; locale: Locale; onClose: () => void; onSaved: () => void }) {
  const t = inventoryText[locale], ref = useRef<HTMLDialogElement>(null); const [action, setAction] = useState<'add' | 'subtract' | 'set'>('add');
  const [stockUnit, setStockUnit] = useState(row.stockUnit ?? 'piece');
  const [quantity, setQuantity] = useState(''), [type, setType] = useState<keyof typeof types>('RECEIPT'), [reason, setReason] = useState(''), [note, setNote] = useState(''), [threshold, setThreshold] = useState(row.lowStockThreshold ?? '0'), [track, setTrack] = useState(!!row.trackInventory), [busy, setBusy] = useState(false), [error, setError] = useState('');
  useEffect(() => { ref.current?.showModal(); }, []);
  let expected = ''; try { expected = changedQuantity(row.stockQuantity ?? '0', action, quantity); } catch { /* Display validation below. */ }
  return <dialog className="inventory-dialog" ref={ref} aria-labelledby="stock-form-title" onCancel={e => { e.preventDefault(); if (!busy) onClose(); }}><h2 id="stock-form-title">{t.edit} — {row.productName[locale]}</h2><p><bdi>{dimensionText(row)} mm</bdi></p><p>{t.current}: {row.stockQuantity} {unitLabels[row.stockUnit ?? 'piece'][locale]}</p>
    <form onSubmit={async e => { e.preventDefault(); setError(''); if (!expected) { setError(t.invalid); return; } setBusy(true); try { await inventoryApi('', locale, { variantId: row.id, version: row.inventoryVersion, action, quantity, type, reason, note, lowStockThreshold: threshold, trackInventory: track, stockUnit }); onSaved(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><fieldset disabled={busy} className="admin-form-body"><div className="admin-grid"><label>{t.edit}<select value={action} onChange={e => { const a = e.target.value as typeof action; setAction(a); setType(a === 'add' ? 'RECEIPT' : a === 'subtract' ? 'SALE' : 'ADJUSTMENT'); }}><option value="add">{t.add}</option><option value="subtract">{t.subtract}</option><option value="set">{t.set}</option></select></label><label>{t.quantity}<input autoFocus required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,3})?" value={quantity} aria-invalid={!!quantity && !expected} onChange={e => setQuantity(e.target.value)}/></label><label>{t.reason}<select value={type} onChange={e => setType(e.target.value as typeof type)}>{Object.entries(types).filter(([key]) => key === 'ADJUSTMENT' || (action === 'add' ? ['RECEIPT','RETURN'].includes(key) : action === 'subtract' ? ['SALE','DAMAGE'].includes(key) : key === 'INITIAL')).map(([key, label]) => <option key={key} value={key}>{t[label]}</option>)}</select></label><label>{t.reason}<input required maxLength={200} value={reason} onChange={e => setReason(e.target.value)}/></label><label>{t.unit}<select value={stockUnit} disabled={!!row.inventoryVersion} onChange={e => setStockUnit(e.target.value as typeof stockUnit)}>{Object.entries(unitLabels).map(([key, labels]) => <option key={key} value={key}>{labels[locale]}</option>)}</select></label><label>{t.threshold}<input required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,3})?" value={threshold} onChange={e => setThreshold(e.target.value)}/></label></div><label className="admin-check"><input type="checkbox" checked={track} onChange={e => setTrack(e.target.checked)}/>{t.track}</label><label>{t.note}<textarea maxLength={2000} value={note} onChange={e => setNote(e.target.value)}/></label><p aria-live="polite">{t.expected}: {expected || '—'} {unitLabels[stockUnit][locale]}</p>{error && <p className="admin-error" role="alert">{error}</p>}<div className="admin-inline"><button type="submit" disabled={busy || !expected}>{t.save}</button><button className="admin-secondary" type="button" onClick={onClose}>{t.cancel}</button></div></fieldset></form>
  </dialog>;
}
function History({ row, locale, onClose }: { row: Row; locale: Locale; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null), t = inventoryText[locale]; const [items, setItems] = useState<Movement[]>([]), [page, setPage] = useState(1), [count, setCount] = useState(0), [error, setError] = useState('');
  useEffect(() => { ref.current?.showModal(); }, []);
  useEffect(() => { let active = true; inventoryApi(`?variantId=${encodeURIComponent(row.id)}&page=${page}`, locale).then(v => { if (active) { setItems(v.items); setCount(v.count); } }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [row.id, page, locale]);
  return <dialog ref={ref} className="inventory-dialog" aria-labelledby="history-title" onCancel={e => { e.preventDefault(); onClose(); }}><h2 id="history-title">{t.history} — {row.productName[locale]}</h2><p><bdi>{dimensionText(row)} mm</bdi></p><button onClick={onClose}>{t.cancel}</button>{error && <p role="alert">{error}</p>}<ol className="inventory-history">{items.map(m => <li key={m.id}><strong>{t[types[m.type as keyof typeof types]]} · {m.quantity} {unitLabels[m.stockUnit][locale]}</strong><p>{t.before}: {m.beforeQuantity} → {t.after}: {m.afterQuantity}</p><p>{t.reason}: {m.reason}</p><p className="admin-preserve">{m.note}</p><small>{t.admin}: {m.admin?.email ?? 'Seed'} · {new Date(m.createdAt).toLocaleString(locale)}</small></li>)}</ol><div className="admin-pagination"><button disabled={page === 1} onClick={() => setPage(p => p - 1)}>{t.previous}</button><span>{page}</span><button disabled={page * 25 >= count} onClick={() => setPage(p => p + 1)}>{t.next}</button></div></dialog>;
}
